apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tp-app-mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: appdb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
