apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-deployer-binding
  namespace: app-prod
subjects:
- kind: ServiceAccount
  name: prod-deployer
  namespace: app-prod
roleRef:
  kind: Role
  name: prod-deployer-role
  apiGroup: rbac.authorization.k8s.io
