apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limitrange
  namespace: app-staging
spec:
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "10m"
      memory: "16Mi"
